### ISSUE TITLE
Tuple keys in psysos.Dict make file unloadable

### ISSUE THREAD

**Issue by Insomniac66** [dagnelies/pysos#15]
Version: `pysos==1.3.0`

MWE:
```python
import pysos

test = pysos.Dict('test')
test[('hello', 'world')] = 'test'
test.close()

test = pysos.Dict('test') # Fails with TypeError: unhashable type: 'list'
```

This seems to be caused by the use of `json.dumps` to encode the key, which will turn the tuple in json list. When the offset dictionary is populated upon opening the file, the key is loaded by `json.loads` as a list.

As for potential resolutions, I can think of three off the top of my head:
- Accept that this doesn't work and simply don't support keys containing tuples
- Configure json.loads to deserialize lists as tuples for dictionary keys (since lists aren't valid dict keys anyway)
- Use the result of `json.dumps` as the key for the offsets dict, incurring the cost of `json.dumps` on every lookup but avoiding issues like this completely.

**Comment by dagnelies** [comment]
> Accept that this doesn't work and simply don't support keys containing tuples

Fine for me 😁 

A workaround is also to simply serialize you tuple as string for the key and vice-versa.
