### ISSUE TITLE
Multiprocessing support

### ISSUE THREAD

**Issue by keeojxexod** [dagnelies/pysos#16]
Hi, thanks for the great lib - it is really the best for store key-value.
Is there a chance that the library will have multiprocessor support?
It is sorely lacking.
Maybe you can suggest ideas on how to add such a feature?

**Comment by dagnelies** [comment]
I don't know exactly what you mean. IO to a file is essentially sequential anyway, and the "synchronisation" of concurrent operations is typically done on a higher level. Or perhaps I didn't understand clearly what you want to achieve.
