### ISSUE TITLE
setdefault() doesn't persist

### ISSUE THREAD

**Issue by doc-hex** [dagnelies/pysos#3]
In python 3.7.5 (at least), the dictionary changes from `setdefault()` are not persisted to disk. They are in memory though.

```python
>>> a = pysos.Dict('test.txt')
>>> b = dict()
>>> a.setdefault('zz', 54)
54
>>> b.setdefault('zz', 54)
54
>>> a
{'zz': 54}
>>> b
{'zz': 54}
>>> print(open('test.txt', 'rt').read())
# FILE-DICT v1

>>>
>>> c = pysos.Dict('test.txt')
>>> c
{}
```

**Comment by dagnelies** [comment]
honestly, I don't think I wanna support this. It looks like a special case to me, which is also Python specific.

The nice thing about such a simple format is that it is "universal". It can also be processed by any text processing tool, or have implementations in other languages like https://github.com/dagnelies/FileMap

Implementing `setdefault` would kind of destroy the simple storage format which are simply lines of key-value pairs and make more difficult for other languages/tool to use/implement it.

Thank you very much for the other pull request though.

**Comment by doc-hex** [comment]
I don't see how that instance method affects file format. It just modifies the state of the (hopefully disk-backed) dictionary.

Regardless, if it's not supported, then you should block it. As it is, a python programmer who uses that method will simply lose data. I suggest overriding that method in your subclass and raising `NotImplementedError` or similar.

**Comment by dagnelies** [comment]
added in latest commit

**Comment by kcwu** [comment]
If you don't want to support all methods of `dict`, `Dict` should not be a subclass of `dict`. Otherwise, it would be surprise to users.

Another example is `get()`. `Dict` didn't implement `get` and thus it always returns None.
