### ISSUE TITLE
module 'chardet' not found

### ISSUE THREAD

**Issue by sina-salahshour** [dagnelies/pysos#4]
chardet is required to be installed manually

**Comment by dagnelies** [comment]
Hmmm... that's annoying ...it's only used for the function to convert a CSV file into a pySOS file. Do you know of a good alternative by chance?

**Comment by dagnelies** [comment]
...my bad ...it's probably missing in the dependencies ...let me check

**Comment by dagnelies** [comment]
well ...I think it's fixed now, please check

**Comment by sina-salahshour** [comment]
> 
> 
> well ...I think it's fixed now, please check

thanks! it works fine now!
