### ISSUE TITLE
Cannot find a way how to fix invalid pysos file

### ISSUE THREAD

**Issue by ukrsms** [dagnelies/pysos#7]
Using pysos I faced an issue when the file became invalid throwing an exception on an attempt to initialize it (pysos.Dict(fileName)). 
As a solution for the situation, I'd have a possibility to remove the file and create an empty new one. Still, after the unsuccessful initialization, the file remains blocked and it cannot be removed until the script is running.
Or maybe there is any regular way how to deal with a problem with an invalid file?

**Comment by dagnelies** [comment]
That is unusual. What is the exact exception? And how was the file "corrupted"? 

Normally, even upon a crash, this should not happen. Only if two separate processes write to this same file.

**Comment by dagnelies** [comment]
Closed due to inactivity

**Comment by ukrsms** [comment]
Hi, in my case, as I suspect,  the failure happened because two separate scripts were using the same file to write.
However, for me, the problem is in an inability to remove the data file if the file is found invalid for any reason.
Finally, I had to move to [shelve ](https://docs.python.org/3/library/shelve.html) component as it allows to solve the problem with invalid file

**Comment by dagnelies** [comment]
Well, you can't remove a file while a script is writing to it... That's kind of normal. That's also why shelve is so inefficient, it keeps opening, writing and closing the file if I remember correctly. If you want to delete the file, you have to stop the script writing to it. Seems common sense to me. 

Basically, writing to the same file from multiple scripts is a bad idea. You are bound to either obtain a corrupted file (in pysos) or loose old data (in shelve).

That said, using pysos, if it's an accident and data was only added (no deletes, no updates) you could possibly open the file with a plain text editor and cut of the part where the content starts to be mixed up.

**Comment by ukrsms** [comment]
In my case, it was an accident when the file got invalid but it indicated to me that if it happened for any reason I wouldn't have a possibility to fix it as my script is considered as fully autonomous

**Comment by dagnelies** [comment]
Well, using shelve you would simply silently lose/overwrite data. Dunno if that's better.

IMHO, better fix your script to ensure they either don't run simultaneously or use different files.
