### ISSUE TITLE
pysos.Dict.get method does not return value even if key exists

### ISSUE THREAD

**Issue by emwadde** [dagnelies/pysos#8]
To avoid KeyError, I tried using the dict's builtin `get` method. But id pysos.Dict it does not seem to work. In my case it always returned `None`. But the internal  `__getitem__` method works as intended. 

The solution for me was to [add](https://github.com/dagnelies/pysos/commit/7858cd5bd7daea87ec86278cfdaaa5cb025d104a) the `get` method to pysos.Dict, which simply calls the `__getitem__`

**Comment by dagnelies** [comment]
Fixed in version 1.2.8
